hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix
- The default microvm's usb passhtrough is not working
- Use qemu extraArgs and udev rules for that
- Pass wireless mesh to netvm
- Pass GPS device to dockervm
=> Passhtrough wireless mesh device and fix usb passhtrough

config-processor-hardware.nix, config-processor-installers.nix, flake.nix, hardware/fmo-os-rugged-laptop-7330-public.nix, hardware/fmo-os-rugged-tablet-7230-public.nix, installers/fmo-os-installer-public.nix, modules/pterm-installer/default.nix, utils/updateAttrs.nix
- Add "updateAttrs" as custom update attributes and lists method, that allow to concatenate lists instead of overwriting them (like lib.recursiveUpdate)
- Add public targets which has a "extend" that indicates the target that they are based on.
- Reconfigure "config-processor-hardware" and "config-processor-installer" for new public targets
=> Add new targets for public build

flake.nix
Hardcode public Hydra build targets as a temporary fix, until
automatic target generation is completed.
=> Configure public Hydra targets

modules/pterm-installer/default.nix
- New version of pterm installer: fix a wifi detecting error when there is ":" in the wifi SSID
=> Update new version of pterm installer

modules/portforwarding-service/default.nix
- proto has been always set to TCP for DNAT forwarding rule
=> Fix portforwarding-service

modules/profiles/applications.nix
- The fmo graphic configs does not overwrite upstream config
- Use lib.mkForce instead of lib.mkDefault
=> Fix a priority error in selecting graphic

modules/graphics/sway/config
- Assign web browser (chromium) to workspace 1
- Assign terminal (foot) to workspace 2
- Keep it as hardcoded because there are not many applications to make the config comlicated
=> Sway - bind applications to different workspace

modules/fmo-dci-service/default.nix
- DOCKER_URL is read from a file, which is generated during registration
- If no file is read, use "cr.airoplatform.com"
=> Add an option that allows to change docker url in fmo-dci service

modules/pterm-installer/default.nix, modules/registration-agent-laptop/default.nix
- Remove systemd service that automatically detects wifi interface
- Add the path to ".env" to pterm-installer environment paths so that the installer can write selected network interface into
=> Update pterm installer with an ability to select network interface

modules/custom-packages/squeekboard/default.nix, modules/custom-packages/squeekboard/us_wide.patch
- Create a new layout and overwrite the default layout via a patch file
- Apply patch before building squeekboard
- New layout is applied for all applications
=> Add custom QWERTY US layout for squeekboard

hardware/fmo-os-rugged-tablet-7230.nix, modules/fmo-psk-distribution-vm/default.nix
- Enable fmo-psk-distribution on host tablet
- Clean up unused code in psk-distribution-vm
=> Fix fmo-psk-distribution service

modules/app-launchers/default.nix, modules/custom-packages/default.nix, modules/custom-packages/terminator/config.patch, modules/custom-packages/terminator/default.nix, modules/graphics/fonts.nix, modules/graphics/sway/config, modules/graphics/sway/sway.nix
- Sway does not support global context menu, therefore, it depends on individual app
- Use "terminator" in replacement of "foot" for context menu support
- Add config for font in "terminator"
- Add "clipman" as clipboard manager, allow retain the clipboard even after the copied source exits
=> Partially support copy/paste feature

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix
- Fix NAT rules to provide dockerapps access through netvm ip
- Add port-forwarding rules to forward UDP traffic also
=> Release 1.0.0b fixes

.github/actions/build-action/entrypoint.sh, .github/actions/upload-action-harbor/upload.sh, .github/actions/upload-action-jfrog/upload.sh, .github/workflows/build.yml
- oras cannot download artifacts uploaded with absolute path
- remove absolute path and use relative
=> CICD: Remove absoulute path in upload actions

config-processor-hardware.nix, hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix, modules/virtualization/microvm/vm.nix, utils/updateHostConfig.nix
- Add host ipaddr and default route to configuration
- Add updateHostConfig functionality
=> FMO-36: Need the host default route to be added

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix, modules/fmo-dci-service/default.nix
- Use default CR URL if file does not exist
- Use CR URL from file if it exists
=> FMO-35: FMO-DCI service needs to read docker container repository URL from file

.github/actions/build-action/entrypoint.sh
- Add '/github/workspace/.git' as safe.directory
- Check if RUNNER_TEMP dir exist
- If not create it
=> FMO-38: CI/CD fatal

modules/desktop/graphics/sway/nwg-panel/default.nix
- Fix an issue that the indicator show 0% battery
- Add upower package as nwg-panel uses it for devices with 2+ batteries
=> fix battery indicator issue on laptop

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix
* For netwm we need to disable systemd.networkd dhcp to keep that manageable only with NetworkManager
=> FMO-52: Systemd.networkd and NetworkManager are not able to work together

config-processor-installers.nix, modules/fmo-services/registration-agent-laptop/default.nix, modules/installers/pterm-installer/default.nix
- Add an option for installer to disable creation of some registration-agent folders, let pterm-installer do that
- Modify env in the installer
- Add symlink path for pterm-installer to create the symlink
- Update pterm-installer with above features
- In the installer system, registration agent runs as if it is running dockervm, with (env=/var/lib/fogdata)
=> FMO-54: Create symlink to installer system

modules/installers/pterm-installer/default.nix
- Keep only internal drive
- Fix hardcoded order of exit screen
=> FMO-66: Update installer with filtered partition

config-processor-installers.nix
- Add fmo-os-installer-debug-compressed and fmo-os-installer-release-compressed
=> FMO-60: Add compressed target for installer image

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix
- One storage common for all VMs:
- /var/vms_shares/common
- One persistence storage dedicated only for every VM:
- /var/lib/internal - for dockervm
- /var/lib/internal - for netvm
- One storage common for VM and Host:
- /var/vms_shares/dockervm -> /var/vms_shares/host
- /var/vms_shares/netvm -> /var/vms_shares/host
=> FMO-21: Persistence storage for VMs, and file transfer

flake.nix, utils/updateAttrs.nix
- Instead of concatenating all the config, indicate which attribute to be overwritten by public build
=> Improve public image filter

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix
- Only networking.wireless or networking.networkmanager can be enabled at a time
=> FMO-53: Fix no wifi detected in netvm due to conflicted config

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix, modules/fmo-certs-distribution-host/default.nix, modules/fmo-module-list.nix, modules/fmo-monitoring/default.nix, modules/google-chrome/overlay.nix
FMO-13: Create dedicated messageVM up and run NATS server on it    
- Add dedicated messageVM
- Add NATS server to messageVM
- Add NATS client to VMs
- Add openssl distribution cert generation and distribution service
FMO-2: Log files to the Message VM    
- Add monitoring service
- Collect journalctl logs and pass them to messageVM
Google chrome also has been updated as it cause build fails
=> FMO-13: FMO-2: monitoringVM, NATS server and services monitoring service

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix, modules/custom-packages/fmo-tool/fmo-tool.nix, modules/custom-packages/vhotplug/vendorid.patch, modules/custom-packages/vhotplug/vhotplug.nix
- Allow passthrough device with exactly-matched vendorid and regex-matched productid
- Update fmo-tool version with vendorname in ddp, allow passthrough device with vendorname using fmo-tool option -vn
- Add default passthrough for device with vendorid "1050"
=> FMO-92: fmo-tool, add ability to passthrough with vendorid and regex-productid

flake.lock, modules/desktop/graphics/sway/sway.ini.nix, modules/desktop/graphics/sway/sway.nix, modules/packages/fmo-qemu/default.nix, modules/profiles/x86.nix, modules/virtualization/microvm/vm.nix
- Update flake.lock for ghaf 24.12
- Currently admin user is used for all VMs, while there could be different users for different VMs
- Temporarily disable hardened greetd.service as it disables sudo (to be used in guivm) but FMO-OS uses gui in host
=> FMO-85: Rebase ghaf 24.12

hardware/fmo-os-rugged-devices.nix, modules/packages/fmo-tool/fmo-tool.nix, modules/packages/vhotplug/vendorid.patch, modules/packages/vhotplug/vhotplug.nix
- Allow passthrough device with exactly-matched vendorid and regex-matched productid
- Update fmo-tool version with vendorname in ddp, allow passthrough device with vendorname using fmo-tool option -vn
- Add default passthrough for device with vendorid "1050"
=> FMO-92: fmo-tool, add ability to passthrough with vendorid main

hardware/fmo-os-rugged-laptop-7330.nix, hardware/fmo-os-rugged-tablet-7230.nix, modules/fmo-dci-passthrough/default.nix, modules/fmo-module-list.nix
- Add fmo-dci-passthrough serivce to help pass USB devices to docker container
=> FMO-86: Passthrough YBkey to dockervm and to docker container inside of dockervm

.github/workflows/build.yml, .github/workflows/check.yml, hardware/fmo-os-rugged-devices.nix
This PR generates the SW version tag during build
[FMO-62](https://jira.tii.ae/browse/FMO-62)
Other updates:
- Update `check.yml` action to use the latest `nix-install-action`
- Use `nix-install-action` and `cachix-action` to handle Nix/Cachix install
- Build the image directly on the runner action instead of separate Docker container
=> FMO-62 with other GH actions updates
